OUTPUT_DIR: "./exp_prw/resnet50"
INPUT:
  DATASET: "PRW"
  DATA_ROOT: "data/PRW"
  BATCH_SIZE_TRAIN: 5
SOLVER:
  MAX_EPOCHS: 20
  BASE_LR: 0.01
MODEL:
  ANCHOR_SIZES: ((32,), (64,), (128,), (256,), (512,))
  ANCHOR_ASPECT_RATIOS: ((0.5, 1.0, 2.0),)
  RPN:
      PRE_NMS_TOPN_TRAIN: 2000
      PRE_NMS_TOPN_TEST: 1000
      POST_NMS_TOPN_TRAIN: 2000
      POST_NMS_TOPN_TEST: 1000
  ROI_HEAD:
      BATCH_SIZE_TRAIN: 512
      POS_FRAC_TRAIN: 0.25
      SCORE_THRESH_TEST: 0.05
      NMS_THRESH_TEST: 0.5
      DETECTIONS_PER_IMAGE_TEST: 100
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
BASELINE:
  PROJECT: True
  TYPE: "baseline"
  BACKBONE_NAME: "resnet50"
  BACKBONE_PRETRAIN: True
  BACKBONE_NECK: True
  FROZENBN2d: False
DISTILLER:
  PROJECT: False
