OUTPUT_DIR: "./exp_cuhk/mobilenetv2_fpn"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "data/CUHK-SYSU"
  BATCH_SIZE_TRAIN: 2
SOLVER:
  MAX_EPOCHS: 20
  BASE_LR: 0.0012
MODEL:
  ANCHOR_SIZES: ((32,), (64,), (128,), (256,), (512,))
  ANCHOR_ASPECT_RATIOS: ((0.5, 1.0, 2.0),)
  RPN:
      PRE_NMS_TOPN_TRAIN: 2000
      PRE_NMS_TOPN_TEST: 1000
      POST_NMS_TOPN_TRAIN: 1000
      POST_NMS_TOPN_TEST: 1000
      SCORE_THRESH: 0.05
  ROI_HEAD:
      BATCH_SIZE_TRAIN: 512
      POS_FRAC_TRAIN: 0.25
      SCORE_THRESH_TEST: 0.05
      NMS_THRESH_TEST: 0.5
      DETECTIONS_PER_IMAGE_TEST: 100
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
BASELINE:
  PROJECT: True
  TYPE: "baseline"
  BACKBONE_NAME: "mobilenet_v2"
  BACKBONE_PRETRAIN: False
  BACKBONE_NECK: True
DISTILLER:
  PROJECT: False