OUTPUT_DIR: "./exp_cuhk/resnet18_fpn/decouple/PKD_1"
INPUT:
  DATASET: "CUHK-SYSU"
  DATA_ROOT: "data/CUHK-SYSU"
SOLVER:
  MAX_EPOCHS: 20
#  BASE_LR: 0.03
#  WEIGHT_DECAY: 0.005
MODEL:
  ANCHOR_SIZES: ((32,), (64,), (128,), (256,), (512,))
  ANCHOR_ASPECT_RATIOS: ((0.5, 1.0, 2.0),)
  RPN:
    PRE_NMS_TOPN_TRAIN: 2000
    PRE_NMS_TOPN_TEST: 1000
    POST_NMS_TOPN_TRAIN: 2000
    POST_NMS_TOPN_TEST: 1000
  ROI_HEAD:
    BATCH_SIZE_TRAIN: 512
    POS_FRAC_TRAIN: 0.25
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.5
    DETECTIONS_PER_IMAGE_TEST: 100
  LOSS:
    LUT_SIZE: 5532
    CQ_SIZE: 5000
BASELINE:
  PROJECT: False
DISTILLER:
  PROJECT: True
  TYPE: "PKD"
  INIT_STUDENT: True
  TEACHER:
    BACKBONE_NAME: "resnet50"
    BACKBONE_PRETRAIN: True
    BACKBONE_NECK: True
    CKPT: "exp_cuhk/resnet50_fpn/v2/baseline_6/epoch_17.pth"
  STUDENT:
    BACKBONE_NAME: "resnet18"
    BACKBONE_PRETRAIN: True
    BACKBONE_NECK: True